improve the hugo server building in CI
Signed-off-by: Rupam-It <mannarupam3@gmail.com>

diff --git a/.github/workflows/hugo-build-status-check.yml b/.github/workflows/hugo-build-status-check.yml
--- a/.github/workflows/hugo-build-status-check.yml
+++ b/.github/workflows/hugo-build-status-check.yml
@@ -41,7 +41,16 @@ jobs:
       - name: Start Hugo server
         run: hugo server --minify --port=8888 &
 
-      # Check if build failed
+      # Step to verify that Hugo server started successfully
+      - name: Verify Hugo server
+        run: |
+          sleep 5  # Wait for a few seconds for the server to start
+          if ! lsof -i:8888; then
+            echo "::error::Hugo server failed to start!"
+            exit 1
+          fi
+
+      # Step to check if build failed
       - name: Check build status
         run: |
           if [ ${{ steps.build.outcome }} != 'success' ]; then
@@ -49,6 +58,13 @@ jobs:
             exit 1
           fi
 
-      # Stop the Hugo server at the end of the workflow as is running in the background
+      # Step to stop the Hugo server at the end of the workflow as it's running in the background
       - name: Stop Hugo server
-        run: kill $(lsof -t -i:8888) || true
+        run: |
+          PID=$(lsof -t -i:8888)
+          if [ -n "$PID" ]; then
+            kill $PID
+            echo "Hugo server stopped."
+          else
+            echo "Hugo server was not running."
+          fi
