check with build then server

diff --git a/.github/workflows/hugo-build-status-check.yml b/.github/workflows/hugo-build-status-check.yml
--- a/.github/workflows/hugo-build-status-check.yml
+++ b/.github/workflows/hugo-build-status-check.yml
@@ -27,20 +27,26 @@ jobs:
           # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
           extended: true
 
-      # Step to start Hugo --minify to validate site and build process
-      - name: Start Hugo
-        run: hugo server --minify
+      # Step to build the site
+      - name: Build site
+        run: hugo --minify
+        # Capture output and error code
+        continue-on-error: true
+        id: build
 
-      # Add other steps here
+      # Step to start Hugo server in the background
+      - name: Start Hugo server
+        run: hugo server --minify --port=8888 &
 
-      # Step to check build status and block commit if build fails
+      # Check if build failed
       - name: Check build status
         run: |
-          if [ $? -ne 0 ]; then
+          if [ ${{ steps.build.outcome }} != 'success' ]; then
             echo "::error::Hugo build failed, blocking commit..."
             exit 1
           fi
 
       # Optionally, add a step to stop the Hugo server at the end of the workflow
-      #- name: Stop Hugo server
-      #  run: kill $(lsof -t -i:8888) || true
+      - name: Stop Hugo server
+        run: kill $(lsof -t -i:8888) || true
+
