Test action, simple test with args
Signed-off-by: Yacine Kheddache <yacine@microcks.io>

diff --git a/.github/workflows/link-checker.yml b/.github/workflows/link-checker.yml
--- a/.github/workflows/link-checker.yml
+++ b/.github/workflows/link-checker.yml
@@ -17,30 +17,30 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      # Step to set up Hugo
-      - name: Setup Hugo
-      uses: peaceiris/actions-hugo@v3
-      with:
-        # Always use the latest version of Hugo, in case of issue with the latest version, 
-        # you can specify a specific version using '0.125.5'
-        hugo-version: 'latest'
-        # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
-        extended: true
+      # # Step to set up Hugo
+      # - name: Setup Hugo
+      # uses: peaceiris/actions-hugo@v3
+      # with:
+      #   # Always use the latest version of Hugo, in case of issue with the latest version, 
+      #   # you can specify a specific version using '0.125.5'
+      #   hugo-version: 'latest'
+      #   # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
+      #   extended: true
 
-      # Step to build the site
-      - name: Build site
-      run: hugo --minify
-      # Capture output and error code
-      continue-on-error: true
-      id: build
+      # # Step to build the site
+      # - name: Build site
+      # run: hugo --minify
+      # # Capture output and error code
+      # continue-on-error: true
+      # id: build
 
-      # Check if build failed
-      - name: Check build status
-      run: |
-        if [ ${{ steps.build.outcome }} != 'success' ]; then
-          echo "::error::Hugo build failed, blocking commit..."
-          exit 1
-        fi
+      # # Check if build failed
+      # - name: Check build status
+      # run: |
+      #   if [ ${{ steps.build.outcome }} != 'success' ]; then
+      #     echo "::error::Hugo build failed, blocking commit..."
+      #     exit 1
+      #   fi
 
       - name: Link Checker
         id: lychee
